<?php

declare(strict_types=1);

namespace App\Service;

class TraefikService
{
    private string $triggerFile;

    public function __construct(?string $triggerFile = null)
    {
        $projectRoot = dirname(__DIR__, 2);
        $dynamicDir = $projectRoot . '/config/traefik/dynamic';
        $this->triggerFile = $triggerFile !== null && $triggerFile !== ''
            ? $triggerFile
            : $dynamicDir . '/onboarding-trigger.yml';
    }

    public function notifyConfigChange(): void
    {
        $directory = dirname($this->triggerFile);
        if (!is_dir($directory) && !mkdir($directory, 0775, true) && !is_dir($directory)) {
            throw new \RuntimeException('Unable to create Traefik dynamic directory');
        }
        if (!is_writable($directory)) {
            throw new \RuntimeException('Traefik dynamic directory not writable');
        }

        $payload = sprintf(
            "# Autogenerated by TraefikService\n# updated: %s\nhttp: {}\n",
            gmdate('c')
        );

        if (file_put_contents($this->triggerFile, $payload) === false) {
            throw new \RuntimeException('Unable to write Traefik trigger file');
        }
    }
}
