apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sommerfest-quiz.fullname" . }}-postgresql
spec:
  serviceName: {{ include "sommerfest-quiz.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sommerfest-quiz.name" . }}-postgresql
  template:
    metadata:
      labels:
        app: {{ include "sommerfest-quiz.name" . }}-postgresql
    spec:
      containers:
        - name: postgres
          image: {{ .Values.database.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.database.name | quote }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.dbSize }}
