[changelog]
header = "# Changelog\n\n"

[git]
filter_unconventional = false

tag_pattern = ".*"

# Skip automatic changelog update commits
commit_parsers = [
  { message = "^docs: update changelog", skip = true },
]
