[changelog]
header = "# Changelog\n\n"

[git]
filter_unconventional = false

tag_pattern = ".*"

# Skip automatic changelog update and version bump commits
commit_parsers = [
  { message = "^docs: update changelog", skip = true },
  { message = "^chore: bump version to", skip = true },
]
