FROM php:8.2.29-alpine

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN apk add --no-cache \
        libpng \
        libjpeg-turbo \
        freetype \
        libwebp \
        libzip \
        postgresql-client \
        imagemagick \
        nodejs \
        npm \
        python3 \
        py3-pip \
    && apk add --no-cache --virtual .build-deps \
        libpng-dev \
        libjpeg-turbo-dev \
        freetype-dev \
        libwebp-dev \
        libzip-dev \
        postgresql-dev \
        imagemagick-dev \
        $PHPIZE_DEPS \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install gd pdo_pgsql exif zip \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && apk del .build-deps \
    && pip3 install --no-cache-dir pytest

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
COPY . /var/www
RUN composer install --no-interaction --prefer-dist --no-progress

COPY config/php.ini /usr/local/etc/php/conf.d/custom.ini

CMD ["composer", "test"]
