ALTER TABLE catalogs ADD COLUMN IF NOT EXISTS event_uid TEXT REFERENCES events(uid) ON DELETE CASCADE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS event_uid TEXT REFERENCES events(uid) ON DELETE CASCADE;
ALTER TABLE results ADD COLUMN IF NOT EXISTS event_uid TEXT REFERENCES events(uid) ON DELETE CASCADE;
ALTER TABLE question_results ADD COLUMN IF NOT EXISTS event_uid TEXT REFERENCES events(uid) ON DELETE CASCADE;
