ALTER TABLE tenants ADD COLUMN IF NOT EXISTS imprint_name TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS imprint_street TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS imprint_zip TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS imprint_city TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS imprint_email TEXT;
