ALTER TABLE events
  ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT FALSE;

UPDATE events SET published = TRUE WHERE published IS NULL;

ALTER TABLE events ALTER COLUMN published SET DEFAULT FALSE;
