-- Add QR design configuration fields
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrLabelLine1 TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrLabelLine2 TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrLabelBottom TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrLogoPath TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrRoundMode TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrLogoPunchout BOOLEAN;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrRounded BOOLEAN;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrColorTeam TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrColorCatalog TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrColorEvent TEXT;
