-- Add QR design configuration fields
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrLabelLine1 TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrLabelLine2 TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrLogoPath TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrRoundMode TEXT;
ALTER TABLE config ADD COLUMN IF NOT EXISTS qrLogoPunchout BOOLEAN;
