CREATE TABLE IF NOT EXISTS redirects (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    target TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 301,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
