ALTER TABLE project_settings
    ADD COLUMN IF NOT EXISTS show_language_toggle BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS show_theme_toggle BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS show_contrast_toggle BOOLEAN NOT NULL DEFAULT TRUE;
