<?php

declare(strict_types=1);

namespace Tests\Service;

use App\Service\TraefikService;
use PHPUnit\Framework\TestCase;

class TraefikServiceTest extends TestCase
{
    public function testNotifyConfigChangeWritesTriggerFile(): void
    {
        $dir = sys_get_temp_dir() . '/traefik' . uniqid();
        mkdir($dir);
        $file = $dir . '/trigger.yml';

        $service = new TraefikService($file);
        $service->notifyConfigChange();

        $this->assertFileExists($file);
        $contents = file_get_contents($file);
        $this->assertNotFalse($contents);
        $this->assertStringContainsString('Autogenerated by TraefikService', $contents ?: '');

        unlink($file);
        rmdir($dir);
    }

    public function testNotifyConfigChangeFailsOnUnwritableDir(): void
    {
        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Traefik dynamic directory not writable');

        $dir = sys_get_temp_dir() . '/traefik' . uniqid();
        mkdir($dir, 0555);
        $file = $dir . '/trigger.yml';

        try {
            $service = new TraefikService($file);
            $service->notifyConfigChange();
        } finally {
            chmod($dir, 0755);
            rmdir($dir);
        }
    }
}
