title: QuizRace Dokumentation

# Theme configuration
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-toc

# Jekyll TOC settings (optional example)
toc:
  min_level: 2
  max_level: 3

# GitHub Repo-Button
github:
  url: https://github.com/bastelix/sommerfest-quiz

color:
  primary: "#5e81ac"
  accent: "#88c0d0"

# Footer-Text
footer: |
  © 2025 QuizRace. Made with ❤️ in Potsdam.
