title: Sommerfest Quiz Dokumentation

# Theme configuration
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-toc

# Jekyll TOC settings (optional example)
toc:
  min_level: 2
  max_level: 3
