<?php

declare(strict_types=1);

return [
    'aurora' => [
        'primary' => '#0ea5e9',
        'accent' => '#22c55e',
        'surface' => '#f8fafc',
        'surfaceMuted' => '#e2e8f0',
        'surfaceDark' => '#0f172a',
        'surfaceMutedDark' => '#1e293b',
        'background' => '#eef2ff',
        'backgroundDark' => '#020617',
        'onAccent' => '#ffffff',
        'textOnSurface' => '#0f172a',
        'textOnBackground' => '#0f172a',
        'textMutedOnSurface' => '#475569',
        'textMutedOnBackground' => '#475569',
        'textOnSurfaceDark' => '#f8fafc',
        'textOnBackgroundDark' => '#f8fafc',
        'textMutedOnSurfaceDark' => '#cbd5e1',
        'textMutedOnBackgroundDark' => '#cbd5e1',
    ],
    'sunset' => [
        'primary' => '#f97316',
        'accent' => '#ec4899',
        'surface' => '#fff7ed',
        'surfaceMuted' => '#fed7aa',
        'surfaceDark' => '#0f172a',
        'surfaceMutedDark' => '#1e293b',
        'background' => '#ffedd5',
        'backgroundDark' => '#020617',
        'onAccent' => '#1f2937',
        'textOnSurface' => '#1f2937',
        'textOnBackground' => '#1f2937',
        'textMutedOnSurface' => '#6b7280',
        'textMutedOnBackground' => '#6b7280',
        'textOnSurfaceDark' => '#f8fafc',
        'textOnBackgroundDark' => '#f8fafc',
        'textMutedOnSurfaceDark' => '#cbd5e1',
        'textMutedOnBackgroundDark' => '#cbd5e1',
    ],
    'midnight' => [
        'primary' => '#6366f1',
        'accent' => '#14b8a6',
        'surface' => '#0f172a',
        'surfaceMuted' => '#1e293b',
        'surfaceDark' => '#0f172a',
        'surfaceMutedDark' => '#1e293b',
        'background' => '#020617',
        'backgroundDark' => '#020617',
        'onAccent' => '#f8fafc',
        'textOnSurface' => '#e2e8f0',
        'textOnBackground' => '#e2e8f0',
        'textMutedOnSurface' => '#94a3b8',
        'textMutedOnBackground' => '#94a3b8',
        'textOnSurfaceDark' => '#f8fafc',
        'textOnBackgroundDark' => '#f8fafc',
        'textMutedOnSurfaceDark' => '#cbd5e1',
        'textMutedOnBackgroundDark' => '#cbd5e1',
    ],
    'monochrome' => [
        'primary' => '#111111',
        'accent' => '#1f1f1f',
        'surface' => '#ffffff',
        'surfaceMuted' => '#f2f2f2',
        'surfaceDark' => '#111111',
        'surfaceMutedDark' => '#1c1c1c',
        'background' => '#f9f9f9',
        'backgroundDark' => '#0a0a0a',
        'onAccent' => '#ffffff',
        'textOnSurface' => '#111111',
        'textOnBackground' => '#111111',
        'textMutedOnSurface' => '#4b4b4b',
        'textMutedOnBackground' => '#4b4b4b',
        'textOnSurfaceDark' => '#f5f5f5',
        'textOnBackgroundDark' => '#f5f5f5',
        'textMutedOnSurfaceDark' => '#bdbdbd',
        'textMutedOnBackgroundDark' => '#bdbdbd',
    ],
];
