<?php

declare(strict_types=1);

/**
 * Generate a Traefik dynamic configuration file that exposes marketing domains.
 */

$projectRoot = dirname(__DIR__);
$defaultTarget = $projectRoot . '/logs/traefik/marketing.yml';
$legacyTargets = [
    $projectRoot . '/config/traefik/dynamic/marketing.yml',
];
$targetPath = $argv[1] ?? getenv('TRAEFIK_MARKETING_CONFIG_PATH') ?: $defaultTarget;
$legacyCleanupTargets = array_values(array_filter(
    $legacyTargets,
    static fn (string $path): bool => $path !== $targetPath,
));

$marketingConfig = (string) getenv('MARKETING_DOMAINS');
$domains = parseMarketingDomains($marketingConfig);

if ($domains === []) {
    removeConfigFile($targetPath, $legacyCleanupTargets);
    exit(0);
}

$rule = buildRule($domains);
$config = buildConfig($rule);

$directory = dirname($targetPath);
if (!is_dir($directory)) {
    if (!mkdir($directory, 0755, true) && !is_dir($directory)) {
        fwrite(STDERR, sprintf("Failed to create directory for %s\n", $targetPath));
        exit(1);
    }
}

if (!is_writable($directory)) {
    fwrite(STDERR, sprintf("Directory is not writable for %s\n", $targetPath));
    exit(1);
}

$existing = file_exists($targetPath) ? (string) file_get_contents($targetPath) : null;
if ($existing === $config) {
    cleanupLegacyConfigs($targetPath, $legacyCleanupTargets);
    exit(0);
}

if (file_put_contents($targetPath, $config) === false) {
    fwrite(STDERR, sprintf("Failed to write marketing Traefik config to %s\n", $targetPath));
    exit(1);
}

if (!chmod($targetPath, 0644)) {
    fwrite(STDERR, sprintf("Warning: unable to adjust permissions for %s\n", $targetPath));
}

cleanupLegacyConfigs($targetPath, $legacyCleanupTargets);

echo sprintf("Updated Traefik marketing router configuration (%d domain%s).\n", count($domains), count($domains) === 1 ? '' : 's');

function parseMarketingDomains(string $value): array
{
    if ($value === '') {
        return [];
    }

    $normalized = str_replace(["\r\n", "\r"], "\n", $value);
    $parts = preg_split('/[\n,]+/', $normalized) ?: [];

    $domains = [];
    foreach ($parts as $part) {
        $host = trim($part);
        if ($host === '') {
            continue;
        }

        if ($host[0] === '~' || strpos($host, '*') !== false) {
            // Ignore regex or wildcard hosts — Traefik certificates require explicit hosts.
            continue;
        }

        if (!isValidHost($host)) {
            fwrite(STDERR, sprintf("Ignoring invalid marketing domain '%s'.\n", $host));
            continue;
        }

        $domains[] = strtolower($host);
    }

    return array_values(array_unique($domains));
}

function isValidHost(string $host): bool
{
    if (strlen($host) > 253) {
        return false;
    }

    $pattern = '/^(?=.{1,253}$)(?!-)(?:[a-z0-9-]{1,63})(?<!-)(?:\.(?!-)(?:[a-z0-9-]{1,63})(?<!-))*\.[a-z]{2,}$/i';

    return (bool) preg_match($pattern, $host);
}

function buildRule(array $domains): string
{
    $hosts = array_map(static fn (string $domain): string => sprintf('Host(`%s`)', $domain), $domains);

    return implode(' || ', $hosts);
}

function buildConfig(string $rule): string
{
    return <<<YAML
# This file is auto-generated by scripts/update_traefik_marketing_domains.php.
# Do not edit manually.
http:
  routers:
    quizrace-marketing-web:
      entryPoints:
        - web
      rule: "$rule"
      middlewares:
        - quizrace-https-redirect@file
      service: quizrace@docker
    quizrace-marketing-secure:
      entryPoints:
        - websecure
      rule: "$rule"
      middlewares:
        - quizrace-security-headers@file
        - quizrace-body-limit-50m@file
      service: quizrace@docker
      tls:
        certResolver: letsencrypt
YAML
    . PHP_EOL;
}

function removeConfigFile(string $targetPath, array $extraTargets = []): void
{
    $paths = array_merge([$targetPath], $extraTargets);

    $seen = [];
    foreach ($paths as $path) {
        if ($path === '') {
            continue;
        }

        if (isset($seen[$path])) {
            continue;
        }
        $seen[$path] = true;

        if (!is_file($path)) {
            continue;
        }

        if (!unlink($path)) {
            fwrite(STDERR, sprintf("Failed to remove marketing Traefik config at %s\n", $path));
            continue;
        }

        if ($path === $targetPath) {
            echo "Removed Traefik marketing router configuration (no domains configured).\n";
        }
    }
}

function cleanupLegacyConfigs(string $activePath, array $legacyTargets): void
{
    foreach ($legacyTargets as $legacyPath) {
        if ($legacyPath === $activePath) {
            continue;
        }

        if (!is_file($legacyPath)) {
            continue;
        }

        if (!unlink($legacyPath)) {
            fwrite(STDERR, sprintf("Warning: unable to remove legacy Traefik marketing config at %s\n", $legacyPath));
        }
    }
}
