<?php

declare(strict_types=1);

/**
 * Generate a Traefik dynamic configuration file that exposes marketing domains.
 */

$projectRoot = dirname(__DIR__);
$defaultTarget = $projectRoot . '/config/traefik/dynamic/marketing.yml';
$targetPath = $argv[1] ?? getenv('TRAEFIK_MARKETING_CONFIG_PATH') ?: $defaultTarget;

$marketingConfig = (string) getenv('MARKETING_DOMAINS');
$domains = parseMarketingDomains($marketingConfig);

if ($domains === []) {
    removeConfigFile($targetPath);
    exit(0);
}

$rule = buildRule($domains);
$config = buildConfig($rule);

if (!is_dir(dirname($targetPath))) {
    if (!mkdir(dirname($targetPath), 0755, true) && !is_dir(dirname($targetPath))) {
        fwrite(STDERR, sprintf("Failed to create directory for %s\n", $targetPath));
        exit(1);
    }
}

$existing = file_exists($targetPath) ? (string) file_get_contents($targetPath) : null;
if ($existing === $config) {
    exit(0);
}

if (file_put_contents($targetPath, $config) === false) {
    fwrite(STDERR, sprintf("Failed to write marketing Traefik config to %s\n", $targetPath));
    exit(1);
}

echo sprintf("Updated Traefik marketing router configuration (%d domain%s).\n", count($domains), count($domains) === 1 ? '' : 's');

function parseMarketingDomains(string $value): array
{
    if ($value === '') {
        return [];
    }

    $normalized = str_replace(["\r\n", "\r"], "\n", $value);
    $parts = preg_split('/[\n,]+/', $normalized) ?: [];

    $domains = [];
    foreach ($parts as $part) {
        $host = trim($part);
        if ($host === '') {
            continue;
        }

        if ($host[0] === '~' || strpos($host, '*') !== false) {
            // Ignore regex or wildcard hosts — Traefik certificates require explicit hosts.
            continue;
        }

        if (!isValidHost($host)) {
            fwrite(STDERR, sprintf("Ignoring invalid marketing domain '%s'.\n", $host));
            continue;
        }

        $domains[] = strtolower($host);
    }

    return array_values(array_unique($domains));
}

function isValidHost(string $host): bool
{
    if (strlen($host) > 253) {
        return false;
    }

    $pattern = '/^(?=.{1,253}$)(?!-)(?:[a-z0-9-]{1,63})(?<!-)(?:\.(?!-)(?:[a-z0-9-]{1,63})(?<!-))*\.[a-z]{2,}$/i';

    return (bool) preg_match($pattern, $host);
}

function buildRule(array $domains): string
{
    $hosts = array_map(static fn (string $domain): string => sprintf('Host(`%s`)', $domain), $domains);

    return implode(' || ', $hosts);
}

function buildConfig(string $rule): string
{
    return <<<YAML
# This file is auto-generated by scripts/update_traefik_marketing_domains.php.
# Do not edit manually.
http:
  routers:
    quizrace-marketing-web:
      entryPoints:
        - web
      rule: "$rule"
      middlewares:
        - quizrace-https-redirect@file
      service: quizrace@docker
    quizrace-marketing-secure:
      entryPoints:
        - websecure
      rule: "$rule"
      middlewares:
        - quizrace-security-headers@file
        - quizrace-body-limit-50m@file
      service: quizrace@docker
      tls:
        certResolver: letsencrypt
YAML
    . PHP_EOL;
}

function removeConfigFile(string $targetPath): void
{
    if (is_file($targetPath)) {
        if (!unlink($targetPath)) {
            fwrite(STDERR, sprintf("Failed to remove marketing Traefik config at %s\n", $targetPath));
            exit(1);
        }
        echo "Removed Traefik marketing router configuration (no domains configured).\n";
    }
}
