site_name: Sommerfest Quiz
theme:
  name: readthedocs
nav:
  - Start: index.md
  - Funktionsweise: funktionsweise.md
  - Vorteile & Nutzen: marketing.md
  - Installation & Schnellstart: installation.md
  - Einstellungen & Anpassung: konfiguration.md
  - Admin & Nutzerverwaltung: verwaltung.md
  - Fragenkataloge: fragenkataloge.md
  - Teams & Ergebnisse: teams-ergebnisse.md
  - Barrierefreiheit: barrierefreiheit.md
  - Datenschutz: datenschutz.md
  - FAQ: faq.md
  - Lizenz & Haftung: lizenz.md
  - Changelog: changelog.md
  - Kontakt: kontakt.md
