name: Build Slim Skeleton

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Optional tag version to push'
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
      - name: Create Slim skeleton
        run: composer create-project slim/slim-skeleton temp-slim
      - name: Copy skeleton files
        run: |
          rsync -a temp-slim/ ./
      - name: Clean up
        run: rm -rf temp-slim
      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update Slim skeleton"
            git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
            git push origin HEAD:${{ github.ref }}
          fi
      - name: Create Tag with PAT
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != ''
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ github.event.inputs.version }}
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin ${{ github.event.inputs.version }}