name: Build Slim Skeleton

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
      - name: Create Slim skeleton
        run: composer create-project slim/slim-skeleton temp-slim
      - name: Copy skeleton files
        run: |
          rsync -a temp-slim/ ./
      - name: Clean up
        run: rm -rf temp-slim
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update Slim skeleton"
            git push
          fi

