name: Manual Composer Install

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Commit updated composer.lock
        run: |
          git config user.name "GH_PAT"
          git config user.email "GH_PAT@users.noreply.github.com"
          if [ -n "$(git status --porcelain composer.lock)" ]; then
            git add composer.lock
            git commit -m "Update composer.lock via workflow"
            git push
          else
            echo "No changes to commit"
          fi
